### PR TITLE
Create 1y24lMaeLch6jPtLCqHgJz?si=80ff908f1c554312

### PR DESCRIPTION
**Pull request by hackjilton**

### CODE REVIEW

**Review by mackorone — CHANGES_REQUESTED** [review]
The filename should only consist of the playlist ID, not additional parts of the URL
```
playlists/registry/1y24lMaeLch6jPtLCqHgJz
```

**Review by mackorone — CHANGES_REQUESTED** [review]
Whoops, it looks like you deleted the old file without adding the new one!

**Comment by hackjilton** [comment]
> Whoops, it looks like you deleted the old file without adding the new one!

Sorry Mack, I'll be honest I have zero clue what I'm doing I just made this account to try and archive a Spotify playlist but I quickly realized I'm in over my head, and am just going to do it manually. So sorry for the bother, if I need to delete anything to get it out of your way let me know.

**Comment by mackorone** [comment]
> So sorry for the bother

You're not a bother! Apologies if I gave you that impression. To save you additional trouble, I'll go ahead and add the playlist myself (and close this PR). Thanks for contributing!

**Comment by hackjilton** [comment]
> > So sorry for the bother
> 
> You're not a bother! Apologies if I gave you that impression. To save you additional trouble, I'll go ahead and add the playlist myself (and close this PR). Thanks for contributing!

No not at all you've been great, I really appreciate your patience and willingness to help. Thanks so much for adding it!

**Comment by maciejpedzich** [comment]
Hey @hackjilton! This is Mac from https://spotifyplaylistarchive.com project, which uses mackorone's repository as a data source and enables users less experienced with Git and GitHub to browse snapshots with more ease.

I've just introduced a new page called [_Get playlist's ID from URL_](https://spotifyplaylistarchive.com/get-playlist-id), which allows you to paste a Spotify playlist link and grab its ID without you having to worry about doing it manually.

Feel free to give it a go, and let me know about your experience! If you believe something needs to be improved - just let me know and I'll sort it out!

**Pull request closed without merging**
