### PR TITLE
Create 0M3835ZhNd7uZxTuhdEdTe

### PR DESCRIPTION
**Pull request by smit-me**

### CODE REVIEW

**Comment by maciejpedzich** [comment]
@mackorone no idea why the bot didn't react to any of those PRs. The last registered downtime was registered last month, and there are no logs on the app-side of things indicating an error. Webhook payloads from GitHub were delivered successfully too.

I'll investigate further should this happen again.

**Comment by mackorone** [comment]
@maciejpedzich it's because the files were created in the project root directory, instead of `playlists/registry`

**Comment by mackorone** [comment]
Two things:
1. Next time, please create a single PR for multiple playlist submissions
1. Next time, make sure to put the files in the `playlists/registry` directory

This time, I've done that for you in https://github.com/mackorone/spotify-playlist-archive/pull/385

**Comment by maciejpedzich** [comment]
> @maciejpedzich it's because the files were created in the project root directory, instead of `playlists/registry`

Ah, forgot to check that - good to know 😅

**Pull request closed without merging**
