### PR TITLE
Create 37i9dQZF1EJIvKFzA8d9hA

### PR DESCRIPTION
**Pull request by Izzy-bellaDotgif**

### CODE REVIEW

**Comment by maciejpedzich** [comment]
Hey @Izzy-bellaDotgif! If you're not sure what your playlist's ID is, you can use [this page](https://spotifyplaylistarchive.com/get-playlist-id) to grab it from a playlist URL.

Once you've got the right ID, go to [the file's page](https://github.com/Izzy-bellaDotgif/spotify-playlist-archive/blob/patch-1/playlists/registry/37i9dQZF1EJIvKFzA8d9hA) and click the pencil icon. Then replace the text inside the small textbox with the ID you've just copied and click **Commit changes**. The playlist-entry-validator bot should be able to identify the playlist and notify the owner that it can be added to the registry!

Let me or mackorone know if you're struggling with anything, we're always happy to help!

**Comment by Izzy-bellaDotgif** [comment]
I was trying to figure out if I could use this for the blend playlist which may be the reason why its not working. Is there anyway to see if it would work?

**Comment by maciejpedzich** [comment]
> I was trying to figure out if I could use this for the blend playlist which may be the reason why its not working. Is there anyway to see if it would work?

I'm afraid it's impossible to archive Blends. From what I've gathered (feel free to correct me if I'm wrong), only you and the users you've invited to that playlist can access it, so if either the archiving script or the validator bot request this playlist's data, Spotify will respond: _this playlist doesn't exist_.

You could work around this by copying the blend's tracklist over to a regular public playlist every time you change the former, and have the latter added to our playlist archive's registry.

**Comment by Izzy-bellaDotgif** [comment]
> > I was trying to figure out if I could use this for the blend playlist which may be the reason why its not working. Is there anyway to see if it would work?
> 
> I'm afraid it's impossible to archive Blends. From what I've gathered (feel free to correct me if I'm wrong), only you and the users you've invited to that playlist can access it, so if either the archiving script or the validator bot request this playlist's data, Spotify will respond: _this playlist doesn't exist_.
> 
> You could work around this by copying the blend's tracklist over to a regular public playlist every time you change the former, and have the latter added to our playlist archive's registry.

I have figured out a shortcut version of what I'm trying to do. Using the app IFTTT, someone created a program that creates an archive of a public or private playlist (because you can link your account to the app) that works similarly to your code. Thank you both for the help, I will look deeper into Spotipy in the future.

Link here: https://ifttt.com/applets/Jkj3QU8B-archive-discover-weekly-blends-any-dynamic-playlist-automatically-without-duplicates

**Pull request closed without merging**
