### PR TITLE
add custom playlist name functionality

### PR DESCRIPTION
**Pull request by catzs**
should be documented, tell me if i made any stupid errors because i'm running on 5 hours of sleep
fixes the issue discussed in #61

### CODE REVIEW

**Comment by catzs** [comment]
except i just realized that you rewrite the files every time, one second

**Comment by catzs** [comment]
i think it will work with a small change because you regenerate the files based on the playlist tuple, but i have to run to class - i'll fix the error when i get back

**Comment by catzs** [comment]
ok so 1st commit was draft 1, 2nd commit was draft 2 (and includes the stupid mistake of not accepting playlist name changes), while 3rd commit is draft 3 (and still has the issue of not accepting playlist name changes, but it only won't accept playlist name changes for playlists that have been 'flagged' per se as having custom names).

**Comment by catzs** [comment]
ok this is a mess i'm goign to do more testing

**Comment by catzs** [comment]
ok finally got it working https://github.com/catzs/spotify-playlist-archive/blob/master/script.py if you're interested

**Comment by mackorone** [comment]
@catzs I thought of a slightly cleaner solution and decided to just implement it: f36a5af36e38ed6312a606681ee5d1f173a01acd. Rather than adding the alternative playlist names to the `plain` files, I created a new `aliases` directory that will contain the playlist aliases information, one file per playlist. I also went ahead and added you "Discover Weekly" playlist to the archive: aa261375b7add045bbe1d06e8e0be2c69d94290f. Feel free to add your other playlists if you want.

**Comment by catzs** [comment]
thanks so much, that's very helpful - i appreciate your cooperation and help

**Pull request closed without merging**
