### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by searching2020**

### CODE REVIEW

**Comment by searching2020** [comment]
trying to add The Other List playlist to the code, not sure if this is what I'm supposed to do

**Comment by mackorone** [comment]
Close, but not quite. Rather than adding a new file that contains 'playlists/plain/...' you should just create a new file with that path (without the angle brackets). It doesn't matter what's in the file - the contents will get replaced the next time the script runs. See if you can use the existing files as a reference, and let me know if you have any questions.

**Review by mackorone — CHANGES_REQUESTED** [review]
Passing this back to you to make changes as described in other comment.

**Comment by searching2020** [comment]
Thanks, think I figured it out!

**Pull request closed without merging**
