### PR TITLE
Create 6KWuVq4sVqCFJmUVCR1aBP

### PR DESCRIPTION
**Pull request by wanniethecharacter**

### CODE REVIEW

**Comment by wanniethecharacter** [comment]
> ### ❌ Playlists for these entries don't exist:
> * https:/open.spotify.com/playlist/6KWuVq4sVqCFJmUVCR1aBP

There is a playlist!!

**Comment by mackorone** [comment]
@wanniethecharacter the filename should just be `6KWuVq4sVqCFJmUVCR1aBP`, not the full playlist URL

**Comment by maciejpedzich** [comment]
> > ### ❌ Playlists for these entries don't exist:
> > * https:/open.spotify.com/playlist/6KWuVq4sVqCFJmUVCR1aBP
> 
> There is a playlist!!

As @mackorone said, you only need to grab the playlist ID, not the entire URL. In the future, you can use [this tool](https://spotifyplaylistarchive.com/get-playlist-id) to extract it from the link.

I'll also add extra checks to detect vaild public playlist URLs in registry file names. If that's the case, the bot will prompt you to rename the file instead of saying the playlist doesn't exist.

Apologies for the confusion and thanks for contributing!

**Comment by mackorone** [comment]
Closing due to inactivity

**Pull request closed without merging**
