### PR TITLE
Create 37i9dQZF1E37gRKKOu8Pkb

### PR DESCRIPTION
**Pull request by catzs**
daily mix 1 for spotify user katzrockso

### CODE REVIEW

**Comment by catzs** [comment]
Also would note that since daily mixes are generated individually based on the account, if more than one person wants one, the names for the pretty files would have to be altered somehow.

**Review by mackorone — CHANGES_REQUESTED** [review]
It's a bit unfortunate, but because we use playlist titles as filenames, we can't archive user-specific playlists; they all have the same name and will collide with one another. If you can somehow rename this playlist to include your username, then we can include it.

**Comment by catzs** [comment]
it's autogenerated by spotify, so i don't think changing the title is possible

**Comment by catzs** [comment]
i think it'd be possible if you included a line in the plain file for custom titles 
and then generated the pretty file name based off of that custom title if it exists
i'm trying to read through the code right now to see where a potential change could be made

**Comment by catzs** [comment]
where are you actually calling plain() from the formatter class, sorry

**Comment by catzs** [comment]
closed until i can think of another solution

**Pull request closed without merging**
