### PR TITLE
Create 37i9dQZF1DXaPCIWxzZwR1

### PR DESCRIPTION
**Pull request by bananabeer19**
pop sauce playlist

### CODE REVIEW

**Comment by mackorone** [comment]
It looks like you included the entire playlist URL in the file path. Can you drop everything after `plain` besides the playlist ID, i.e., `37i9dQZF1DXaPCIWxzZwR1`?

**Review by mackorone — CHANGES_REQUESTED** [review]
The file path should be `playlists/plain/37i9dQZF1DXaPCIWxzZwR1`

**Comment by bananabeer19** [comment]
> The file path should be `playlists/plain/37i9dQZF1DXaPCIWxzZwR1`

i am sorry i have no idea how github works, i just joined like 3 days back xD

**Comment by mackorone** [comment]
> i am sorry i have no idea how github works

No worries, this pull request was nearly perfect! You created a file called:

`playlists/plain/https:/open.spotify.com/playlist/37i9dQZF1DXaPCIWxzZwR1`

You just need to change it to:

`playlists/plain/37i9dQZF1DXaPCIWxzZwR1`

You can do so like this:

```
$ cd spotify-playlist-archive  # navigate to the project root
$ git mv playlists/plain/https:/open.spotify.com/playlist/37i9dQZF1DXaPCIWxzZwR1 playlists/plain/37i9dQZF1DXaPCIWxzZwR1
$ git amend  # update your local commit
$ git push  # update your pull request
```

Let me know if you have any other questions, happy to help!

**Comment by bananabeer19** [comment]
> > i am sorry i have no idea how github works
> 
> No worries, this pull request was nearly perfect! You created a file called:
> 
> `playlists/plain/https:/open.spotify.com/playlist/37i9dQZF1DXaPCIWxzZwR1`
> 
> You just need to change it to:
> 
> `playlists/plain/37i9dQZF1DXaPCIWxzZwR1`
> 
> You can do so like this:
> 
> ```shell
> $ cd spotify-playlist-archive  # navigate to the project root
> $ git mv playlists/plain/https:/open.spotify.com/playlist/37i9dQZF1DXaPCIWxzZwR1 playlists/plain/37i9dQZF1DXaPCIWxzZwR1
> $ git amend  # update your local commit
> $ git push  # update your pull request
> ```
> 
> Let me know if you have any other questions, happy to help!



> > i am sorry i have no idea how github works
> 
> No worries, this pull request was nearly perfect! You created a file called:
> 
> `playlists/plain/https:/open.spotify.com/playlist/37i9dQZF1DXaPCIWxzZwR1`
> 
> You just need to change it to:
> 
> `playlists/plain/37i9dQZF1DXaPCIWxzZwR1`
> 
> You can do so like this:
> 
> ```shell
> $ cd spotify-playlist-archive  # navigate to the project root
> $ git mv playlists/plain/https:/open.spotify.com/playlist/37i9dQZF1DXaPCIWxzZwR1 playlists/plain/37i9dQZF1DXaPCIWxzZwR1
> $ git amend  # update your local commit
> $ git push  # update your pull request
> ```
> 
> Let me know if you have any other questions, happy to help!



> The file path should be `playlists/plain/37i9dQZF1DXaPCIWxzZwR1`

**Comment by mackorone** [comment]
Looks good!

**Pull request merged**
